parameters: {}
environment:
  OPENAI_API_KEY: "${OPENAI_API_KEY}"
  MONGO_URI: "${MONGO_URI}"
packages:
  - name: rag
    shared: false
    environment:
      LOG_LEVEL: warn
    parameters: {}
    annotations: {}
    functions:
      - name: send-for-embed
        runtime: nodejs:18
        limits:
          timeout: 850000
          memory: 512
      - name: retrieve-embed
        runtime: nodejs:18
        limits:
          timeout: 850000
          memory: 512
        environment:
          WEAVIATE_API_KEY: "${WEAVIATE_API_KEY}"
          WEAVIATE_API_HOST: "${WEAVIATE_API_HOST}"
